from pathlib import Path

from udemy_toolkit.extract import (
    captions_to_transcript,
    format_seconds,
    parse_cues,
)

FIXTURE = Path(__file__).parent / "fixtures" / "udemy" / "sample_captions.vtt"


def test_format_seconds():
    assert format_seconds(0) == "00:00:00"
    assert format_seconds(3723) == "01:02:03"


def test_parse_cues_reads_starts_strips_markup_and_drops_blanks():
    cues = parse_cues(FIXTURE.read_text(encoding="utf-8"))
    assert cues == [
        (1, "first line here"),
        (4, "second line here"),
        (3723, "much later line"),
    ]


def test_parse_cues_on_empty_input():
    assert parse_cues("") == []
    assert parse_cues("WEBVTT\n\n") == []


def test_transcript_groups_cues_into_timestamped_paragraphs():
    text = captions_to_transcript(FIXTURE.read_text(encoding="utf-8"))
    paragraphs = text.split("\n\n")
    assert paragraphs[0] == "[00:00:00] first line here second line here"
    assert paragraphs[1] == "[01:02:00] much later line"


def test_transcript_of_captionless_input_is_empty_string():
    assert captions_to_transcript("") == ""


def test_parse_cues_handles_short_form_timestamps_without_hours():
    """Regression: Udemy's own autogenerated captions use WebVTT's valid
    short form under an hour (MM:SS.mmm, no hours group) -- confirmed live
    against a real course. The strict HH:MM:SS-only regex silently dropped
    every cue in such a file, so has_transcript was False despite the caption
    text actually being fetched successfully.
    """
    raw = (
        "WEBVTT\n\n"
        "0\n"
        "00:00.510 --> 00:03.313\n"
        "Welcome to this course.\n\n"
        "1\n"
        "00:03.313 --> 00:06.035\n"
        "I've split it up.\n"
    )
    cues = parse_cues(raw)
    assert cues == [
        (0, "Welcome to this course."),
        (3, "I've split it up."),
    ]
    assert captions_to_transcript(raw) != ""
