"""End-to-end integration test of the crawl ORCHESTRATION.

The live portal needs Playwright + an interactive login, which can't run in CI.
So we drive the *real* ``crawler.crawl()`` (and ``_crawl_course``, ``_read_syllabus``,
``_read_summary``, the parsers, and ``save_catalog``) against a fake Playwright
``page`` that **replays the real DOM captured from the authenticated SOIC portal**
(the "Important Membership Updates" course: 2 sections, 6 lessons, 1 video with an
AI summary). Only the browser transport is faked; every line of crawl logic runs.

This is the integration counterpart to test_portal.py (which unit-tests the
parsers/extractors). Together they execute the full crawl pipeline end to end.
"""

from __future__ import annotations

import contextlib

import pytest

from soic_toolkit import crawler
from soic_toolkit.models import Catalog

BASE = "https://learn.soic.in"
BUNDLE_URL = f"{BASE}/learn/home/SOIC-Course"
S1 = f"{BASE}/learn/home/SOIC-Course/Important-Membership-Updates/section/589476"

# --- Real DOM captured live from the authenticated portal -------------------
COURSE_TITLE = "Important Membership Updates"

# What _SHADOW_WALK returns on the course page (rendered order), as actually seen.
SYLLABUS_ROWS = [
    {"kind": "section", "text": "01 Important Membership Updates 4 Lessons • 2 Attachments"},
    {"kind": "lesson", "text": "Must Watch Intro Video Video • 4m 30s"},
    {"kind": "lesson", "text": "Must Read: Guide to Membership + Telegram Group Article • Attachment"},
    {"kind": "lesson", "text": "SOIC Membership Content Index Article •"},
    {"kind": "lesson", "text": "Membership Renewal Plans Article • Attachment"},
    {"kind": "section", "text": "02 Zoom Links For Live Classes 2 Lessons • 1 Attachment"},
    {"kind": "lesson", "text": "How to Use Zoom Links Article •"},
    {"kind": "lesson", "text": "21.06.26 Zoom Link Article • Attachment"},
]

# Resolved lesson URLs (real IDs where captured; fixture IDs otherwise).
LESSON_URLS = {
    "Must Watch Intro Video": f"{S1}/lesson/4830058",
    "Must Read: Guide to Membership + Telegram Group": f"{S1}/lesson/4606989",
    "SOIC Membership Content Index": f"{S1}/lesson/3681040",
    "Membership Renewal Plans": f"{S1}/lesson/4606990",
    "How to Use Zoom Links": f"{S1}/lesson/4606991",
    "21.06.26 Zoom Link": f"{S1}/lesson/4606992",
}

# The real AI summary the portal rendered for the intro video (with the per-user
# watermark line + AI header that clean_summary must strip).
RAW_SUMMARY = (
    "Lesson summary generated by AI\n"
    "SOIC Membership Overview\n"
    "Introduction to SOIC Membership\n"
    "syedamber91@gmail.com\n"
    "The SOIC membership offers a comprehensive learning experience for investors "
    "of all levels. The program is structured into distinct levels covering finance "
    "and investing, with courses, masterclasses, and regular market updates in both "
    "Hindi and English. Materials are refreshed every three years and members join "
    "weekly webinars to keep learning."
)


class _Locator:
    def __init__(self, page, text):
        self.page, self.text = page, text

    @property
    def first(self):
        return self

    def click(self, timeout=None):
        self.page._click_text(self.text)


class _FakePage:
    """Replays the captured portal DOM through the Playwright Page surface used by crawler."""

    def __init__(self):
        self.url = ""
        self.state = "start"          # start -> bundle -> course -> lesson
        self.current_lesson = None

    def goto(self, url, wait_until=None):
        self.url = url
        if url.rstrip("/") == BUNDLE_URL:
            self.state = "bundle"

    def wait_for_timeout(self, ms):  # no real waiting in the test
        return None

    def get_by_text(self, text, exact=False):
        return _Locator(self, text)

    def _click_text(self, text):
        if text == "Summary":
            return  # stays on the lesson; summary tab opens
        if text == COURSE_TITLE and self.state == "bundle":
            self.state = "course"
            self.url = f"{S1}/lesson/4830058"  # course landing
            return
        if text in LESSON_URLS:
            self.state = "lesson"
            self.current_lesson = text
            self.url = LESSON_URLS[text]
            return

    def evaluate(self, js):
        if js is crawler._SHADOW_WALK:
            return SYLLABUS_ROWS if self.state in ("course", "lesson") else []
        if js is crawler._SUMMARY_EXTRACT:
            return RAW_SUMMARY if self.current_lesson == "Must Watch Intro Video" else ""
        # else: the inline _course_cards walker
        return [COURSE_TITLE] if self.state == "bundle" else []


class _FakeContext:
    def new_page(self):
        return _FakePage()


@pytest.fixture
def wired(tmp_path, monkeypatch):
    content = tmp_path / "content.json"
    monkeypatch.setattr(crawler, "CONTENT_PATH", content)
    monkeypatch.setattr(crawler, "ensure_dirs", lambda: None)
    monkeypatch.setattr(crawler, "BUNDLE_SLUGS", ["SOIC-Course"])
    monkeypatch.setattr(crawler, "_polite_sleep", lambda: None)
    monkeypatch.setenv("SOIC_WATERMARK_LINES", "syedamber91@gmail.com")

    @contextlib.contextmanager
    def fake_ctx():
        yield _FakeContext()

    monkeypatch.setattr(crawler, "authenticated_context", fake_ctx)
    return content


def test_crawl_full_orchestration(wired):
    catalog = crawler.crawl()

    # one course, with the two real sections preserved as modules (correct grouping)
    assert len(catalog.courses) == 1
    course = catalog.courses[0]
    assert course.title == COURSE_TITLE
    assert [m.title for m in course.modules] == [
        "Important Membership Updates",
        "Zoom Links For Live Classes",
    ]

    lessons = [l for m in course.modules for l in m.lessons]
    assert len(lessons) == 6
    # every lesson resolved a real URL via the click step
    assert all(l.url.startswith(S1) for l in lessons)

    intro = next(l for l in lessons if l.title == "Must Watch Intro Video")
    assert intro.lesson_type == "video" and intro.duration == "4m 30s"
    # AI summary captured + cleaned: watermark + "generated by AI" header stripped
    assert intro.ai_summary
    assert "syedamber91@gmail.com" not in intro.ai_summary
    assert "generated by AI" not in intro.ai_summary.lower()
    assert intro.key_points  # derived from the summary

    # articles captured as structure-only (no body/summary) — guardrail honored
    articles = [l for l in lessons if l.lesson_type == "article"]
    assert len(articles) == 5
    assert all(a.ai_summary == "" for a in articles)
    assert any(a.has_attachment for a in articles)


def test_crawl_persists_resumable_catalog(wired):
    crawler.crawl()
    # the orchestration wrote a valid, reloadable catalog to disk
    assert wired.exists()
    reloaded = Catalog.model_validate_json(wired.read_text(encoding="utf-8"))
    assert len(reloaded.lesson_urls()) == 6


def test_crawl_rerun_is_resumable_no_duplicates(wired):
    crawler.crawl()
    catalog = crawler.crawl()  # second run must not duplicate the course
    assert len(catalog.courses) == 1
    lessons = [l for m in catalog.courses[0].modules for l in m.lessons]
    assert len(lessons) == 6
