"""Tests for the Learnyst "Bodhi" portal helpers in extract.py.

Samples are real rendered strings captured from a logged-in learn.soic.in
session (see docs/PORTAL_NOTES.md). These validate the pure parsing/cleaning
logic without a live login or browser.
"""

from soic_toolkit.extract import (
    clean_summary,
    parse_lesson_meta,
    parse_section_header,
)


class TestParseSectionHeader:
    def test_with_attachments(self):
        out = parse_section_header("01 Important Membership Updates 4 lessons • 2 attachments")
        assert out == {
            "number": 1,
            "title": "Important Membership Updates",
            "lesson_count": 4,
            "attachment_count": 2,
        }

    def test_no_spaces_variant(self):
        # Shadow-DOM text often concatenates without spaces.
        out = parse_section_header("02Zoom Links For Live Classes2 lessons • 1 attachment")
        assert out["number"] == 2
        assert out["title"] == "Zoom Links For Live Classes"
        assert out["lesson_count"] == 2
        assert out["attachment_count"] == 1

    def test_without_attachments(self):
        out = parse_section_header("03 Valuation Basics 12 lessons")
        assert out["attachment_count"] == 0
        assert out["lesson_count"] == 12

    def test_non_header_returns_none(self):
        assert parse_section_header("Must Watch Intro Video Video • 4m 30s") is None
        assert parse_section_header("") is None


class TestParseLessonMeta:
    def test_video_with_duration_full_row(self):
        out = parse_lesson_meta("Must Watch Intro Video Video • 4m 30s")
        assert out["lesson_type"] == "video"
        assert out["duration"] == "4m 30s"  # full compound duration
        assert out["has_attachment"] is False

    def test_article_with_attachment(self):
        out = parse_lesson_meta("Membership Renewal Plans Article • attachment")
        assert out["lesson_type"] == "article"
        assert out["has_attachment"] is True
        assert out["duration"] is None

    def test_article_no_meta(self):
        out = parse_lesson_meta("SOIC Membership Content Index Article")
        assert out["lesson_type"] == "article"
        assert out["has_attachment"] is False

    def test_meta_tail_only(self):
        out = parse_lesson_meta("Video • 12m")
        assert out["lesson_type"] == "video"
        assert out["duration"] == "12m"


class TestCleanSummary:
    def test_strips_ai_header_and_watermark(self):
        raw = (
            "Lesson summary generated by AI\n"
            "SOIC Membership Overview\n"
            "syedamber91@gmail.com\n"
            "+918885745325\n"
            "The SOIC membership offers a comprehensive learning experience.\n"
        )
        out = clean_summary(raw, watermark_lines=["syedamber91@gmail.com", "+918885745325"])
        assert "generated by AI" not in out
        assert "syedamber91@gmail.com" not in out
        assert "+918885745325" not in out
        assert "SOIC Membership Overview" in out
        assert "comprehensive learning experience" in out

    def test_generic_email_phone_heuristics(self):
        raw = "Key idea here.\nsomeone@example.com\n+1 800 555 1234\nAnother point."
        out = clean_summary(raw)
        assert "someone@example.com" not in out
        assert "Key idea here." in out
        assert "Another point." in out

    def test_empty(self):
        assert clean_summary("") == ""
