"""Walk the membership content on learn.soic.in (Learnyst "Bodhi") and capture
structure + openly-rendered AI summaries.

This portal is a Next.js + Bodhi-web-component PWA: there are no content anchors,
everything lives in Shadow DOM, and lesson/section IDs only appear in the URL
after the framework navigates. So discovery is **click-driven** and extraction
reads already-rendered TEXT from the (open) shadow DOM via ``page.evaluate``.
See ``docs/PORTAL_NOTES.md`` for the full reconnaissance.

Scope (deliberate, see PORTAL_NOTES "Capture-scope decision"):
  * Captured: hierarchy (bundle→course→section→lesson), titles, type, duration,
    attachment flags, and the AI-generated per-lesson summary.
  * NOT captured: article bodies (sandboxed iframe + watermark + "prohibited"
    notice — extraction would require circumventing protection) and verbatim
    video transcripts (the protected video's content in text form).
"""

from __future__ import annotations

import os
import random
import time
from datetime import datetime, timezone
from typing import Optional

from playwright.sync_api import BrowserContext, Page
from rich.console import Console

from .auth import authenticated_context
from .config import CONTENT_PATH, ensure_dirs, settings
from .extract import (
    clean_summary,
    derive_key_points,
    parse_lesson_meta,
    parse_section_header,
)
from .models import Catalog, Course, Lesson, Module

console = Console()

# Comma-separated bundle slugs to crawl, e.g. "SOIC-Course". The membership
# bundle is "SOIC-Course". Override via SOIC_BUNDLE_SLUGS in .env.
BUNDLE_SLUGS = [
    s.strip()
    for s in os.environ.get("SOIC_BUNDLE_SLUGS", "SOIC-Course").split(",")
    if s.strip()
]

# JS injected into the page to read text across open Shadow DOM. Returned by
# page.evaluate(); never touches the sandboxed article iframe or media.
_SHADOW_WALK = r"""
() => {
  function* walk(root){
    for (const el of root.querySelectorAll('*')) {
      yield el;
      if (el.shadowRoot) yield* walk(el.shadowRoot);
    }
  }
  const all = [...walk(document)];
  // Section headers + lesson rows, in rendered order.
  const sectionRe = /^\s*\d{1,3}\s*.+?\s*\d+\s*lessons?/i;
  const lessonRe = /(video|article|quiz|pdf|live)\s*[•·]/i;
  const seen = new Set();
  const rows = [];
  for (const el of all) {
    const t = (el.textContent || '').replace(/\s+/g,' ').trim();
    if (!t || t.length > 160 || seen.has(t)) continue;
    const kids = el.querySelectorAll('*').length;
    if (sectionRe.test(t) && kids < 14) { seen.add(t); rows.push({kind:'section', text:t}); }
    else if (lessonRe.test(t) && kids >= 1 && kids <= 10) { seen.add(t); rows.push({kind:'lesson', text:t}); }
  }
  return rows;
}
"""

_SUMMARY_EXTRACT = r"""
() => {
  function* walk(root){
    for (const el of root.querySelectorAll('*')) {
      yield el;
      if (el.shadowRoot) yield* walk(el.shadowRoot);
    }
  }
  const all = [...walk(document)];
  let best = null, len = 0;
  for (const el of all) {
    if (el.tagName === 'STYLE' || el.tagName === 'SCRIPT') continue;
    const t = el.innerText || '';
    if (t.length > len && t.length < 20000 && /generated by AI|Overview|Introduction/i.test(t)) {
      // prefer the tightest block that still holds real prose
      best = el; len = t.length;
    }
  }
  return best ? best.innerText : '';
}
"""


def load_catalog() -> Catalog:
    if CONTENT_PATH.exists():
        return Catalog.model_validate_json(CONTENT_PATH.read_text(encoding="utf-8"))
    return Catalog(base_url=settings.base_url)


def save_catalog(catalog: Catalog) -> None:
    ensure_dirs()
    CONTENT_PATH.write_text(catalog.model_dump_json(indent=2), encoding="utf-8")


def _polite_sleep() -> None:
    time.sleep(random.uniform(settings.crawl_min_delay, settings.crawl_max_delay))


def _bundle_url(slug: str) -> str:
    return f"{settings.base_url.rstrip('/')}/learn/home/{slug}"


def _read_syllabus(page: Page) -> list[dict]:
    """Return ordered rows ``[{kind:'section'|'lesson', text}]`` from the syllabus."""
    try:
        return page.evaluate(_SHADOW_WALK) or []
    except Exception:
        return []


def _read_summary(page: Page) -> str:
    """Open the Summary tab and return the cleaned AI summary (may be empty)."""
    try:
        # The Summary tab is a Bodhi-rendered control; click by its text.
        page.get_by_text("Summary", exact=True).first.click(timeout=4000)
        page.wait_for_timeout(3500)  # AI summary loads async
        raw = page.evaluate(_SUMMARY_EXTRACT) or ""
    except Exception:
        return ""
    # Strip the per-user watermark (the logged-in identity) and AI header.
    watermark = [v for v in (os.environ.get("SOIC_WATERMARK_LINES", "").split("|")) if v]
    return clean_summary(raw, watermark_lines=watermark)


def _course_cards(page: Page) -> list[str]:
    """Titles of course cards on a bundle page (used to click into each)."""
    try:
        rows = page.evaluate(
            r"""() => {
              function* walk(root){for(const el of root.querySelectorAll('*')){yield el; if(el.shadowRoot) yield* walk(el.shadowRoot);}}
              const out=[], seen=new Set();
              for(const el of walk(document)){
                const t=(el.textContent||'').replace(/\s+/g,' ').trim();
                const m=t.match(/^(.+?)\s*Course\s*[•·]\s*\d+\s*lessons?$/i);
                if(m && t.length<120 && !seen.has(m[1])){seen.add(m[1]); out.push(m[1].trim());}
              }
              return out;
            }"""
        )
        return rows or []
    except Exception:
        return []


def _crawl_course(page: Page, course: Course, limit: Optional[int], captured: int,
                  already: set[str]) -> int:
    """Walk one course's sections/lessons, capturing summaries. Returns new count."""
    rows = _read_syllabus(page)
    current_section: Optional[Module] = None
    course.modules = []

    # First pass: build section/lesson skeleton from the rendered syllabus order.
    for row in rows:
        if row["kind"] == "section":
            hdr = parse_section_header(row["text"])
            title = hdr["title"] if hdr else row["text"]
            current_section = Module(title=title)
            course.modules.append(current_section)
        else:
            if current_section is None:
                current_section = Module(title=course.title)
                course.modules.append(current_section)
            meta = parse_lesson_meta(row["text"])
            # Title is the row text with the trailing type/meta removed.
            title = row["text"]
            if meta["lesson_type"]:
                idx = title.lower().rfind(meta["lesson_type"])
                if idx > 0:
                    title = title[:idx].strip()
            current_section.lessons.append(
                Lesson(
                    title=title or row["text"],
                    url="",  # filled in when we click into it
                    lesson_type=meta["lesson_type"],
                    duration=meta["duration"],
                    has_attachment=meta["has_attachment"],
                )
            )

    # Second pass: click each lesson row to resolve its URL + AI summary.
    for section in course.modules:
        for lesson in section.lessons:
            if limit is not None and captured >= limit:
                return captured
            try:
                page.get_by_text(lesson.title, exact=False).first.click(timeout=4000)
                page.wait_for_timeout(1500)
                lesson.url = page.url
                if lesson.url in already and lesson.ai_summary:
                    continue
                if lesson.lesson_type == "video":
                    lesson.ai_summary = _read_summary(page)
                    if lesson.ai_summary:
                        lesson.key_points = derive_key_points(lesson.ai_summary)
                lesson.crawled_at = datetime.now(timezone.utc)
                captured += 1
                console.print(f"    [cyan]captured[/cyan] {lesson.title[:60]}")
                _polite_sleep()
            except Exception as exc:  # noqa: BLE001 — skip a stubborn lesson, keep going
                console.print(f"    [red]skip[/red] {lesson.title[:50]}: {exc}")
    return captured


def crawl(limit: Optional[int] = None) -> Catalog:
    """Discover bundle→course→section→lesson structure and capture AI summaries.

    Resumable: re-running skips lessons already captured (URL + summary present).
    """
    catalog = load_catalog()
    already = catalog.lesson_urls()
    captured = 0

    with authenticated_context() as context:  # type: BrowserContext
        page = context.new_page()

        for slug in BUNDLE_SLUGS:
            console.print(f"[bold]Bundle[/bold] {slug}")
            page.goto(_bundle_url(slug), wait_until="domcontentloaded")
            page.wait_for_timeout(3000)
            course_titles = _course_cards(page)
            console.print(f"  discovered {len(course_titles)} course(s)")

            for title in course_titles:
                if limit is not None and captured >= limit:
                    save_catalog(catalog)
                    console.print(f"[green]Reached limit of {limit}.[/green]")
                    return catalog
                # Reuse an existing course of the same title so re-runs stay
                # resumable instead of appending a duplicate each time.
                course = next(
                    (c for c in catalog.courses if c.title == title), None
                )
                if course is None:
                    course = Course(title=title)
                    catalog.courses.append(course)
                console.print(f"  • {title}")
                try:
                    # Re-open the bundle page, then click into this course.
                    page.goto(_bundle_url(slug), wait_until="domcontentloaded")
                    page.wait_for_timeout(2500)
                    page.get_by_text(title, exact=False).first.click(timeout=5000)
                    page.wait_for_timeout(3000)
                    course.url = page.url
                    captured = _crawl_course(page, course, limit, captured, already)
                    save_catalog(catalog)  # incremental — resumable on crash
                except Exception as exc:  # noqa: BLE001
                    console.print(f"  [red]skip course[/red] {title}: {exc}")

    save_catalog(catalog)
    console.print(f"[green]Done. Captured {captured} lesson summaries.[/green]")
    return catalog
