export const C = {
  blue:     "var(--blue)",
  blueBg:   "var(--blue-bg)",
  green:    "var(--green)",
  greenBg:  "var(--green-bg)",
  amber:    "var(--amber)",
  amberDk:  "var(--amber-dk)",
  amberBg:  "var(--amber-bg)",
  red:      "var(--red)",
  redBg:    "var(--red-bg)",
  teal:     "var(--teal)",
  tealBg:   "var(--teal-bg)",
  gray10:   "var(--gray-10)",
  gray30:   "var(--gray-30)",
  gray50:   "var(--gray-50)",
  gray70:   "var(--gray-70)",
  gray90:   "var(--gray-90)",
  gray95:   "var(--gray-95)",
  gray97:   "var(--gray-97)",
  border:   "var(--border)",
} as const;
